import mount from "@test";
import renderer from "react-test-renderer";
import TodoList from "../TodoList";

// auto generated by react-automate-pro test will fail
describe(TodoList, () => {
  const component = mount(<TodoList />);

  it("renders without crashing", () => {
    expect(component).toBeTruthy();
    const componentRender = renderer.create(<TodoList />);
    const tree = componentRender.toJSON();
    expect(tree).toMatchSnapshot();
  });

  it("Should have the correct class name", () => {
    expect(component.find("todoList")).toEqual(1);
  });
});
