import mount from "@test";
import renderer from "react-test-renderer";
import Todos from "../Todos";

// auto generated by react-automate-pro test will fail
describe(Todos, () => {
  const component = mount(<Todos />);

  it("renders without crashing", () => {
    expect(component).toBeTruthy();
    const componentRender = renderer.create(<Todos />);
    const tree = componentRender.toJSON();
    expect(tree).toMatchSnapshot();
  });

  it("Should have the correct class name", () => {
    expect(component.find("todos")).toEqual(1);
  });
});
